package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FcAttore generated by hbm2java
 */
@Entity
@Table(name = "fc_attore" )
public class FcAttore implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAttore;
	private String cellulare;
	private String cognome;
	private String descAttore;
	private String username;
	private String email;
	private String nome;
	private boolean notifiche;
	private String password;
	private boolean admin;
	private boolean active;
	private String style;
	private Set<FcClassifica> fcClassificas = new HashSet<FcClassifica>(0);
	private Set<FcGiornataRis> fcGiornataRises = new HashSet<FcGiornataRis>(0);
	private Set<FcClassificaTotPt> fcClassificaTotPts = new HashSet<FcClassificaTotPt>(0);
	private Set<FcFormazione> fcFormaziones = new HashSet<FcFormazione>(0);
	private Set<FcGiornataDett> fcGiornataDetts = new HashSet<FcGiornataDett>(0);
	private Set<FcGiornataDettInfo> fcGiornataDettInfos = new HashSet<FcGiornataDettInfo>(0);
	private Set<FcMercatoDett> fcMercatoDetts = new HashSet<FcMercatoDett>(0);
	private Set<FcGiornata> fcGiornatasForIdAttoreFuori = new HashSet<FcGiornata>(0);
	private Set<FcGiornata> fcGiornatasForIdAttoreCasa = new HashSet<FcGiornata>(0);

	public FcAttore() {
	}

	public FcAttore(int idAttore, String cellulare, String cognome,
			String descAttore, String username,String email, String nome, boolean notifiche) {
		this.idAttore = idAttore;
		this.cellulare = cellulare;
		this.cognome = cognome;
		this.descAttore = descAttore;
		this.username = username;
		this.email = email;
		this.nome = nome;
		this.notifiche = notifiche;
	}

	public FcAttore(int idAttore, String cellulare, String cognome,
			String descAttore, String username,String email, String nome,
			boolean notifiche, String password, Set<FcClassifica> fcClassificas,
			Set<FcGiornataRis> fcGiornataRises,
			Set<FcClassificaTotPt> fcClassificaTotPts,
			Set<FcFormazione> fcFormaziones,
			Set<FcGiornataDett> fcGiornataDetts,
			Set<FcGiornataDettInfo> fcGiornataDettInfos,
			Set<FcMercatoDett> fcMercatoDetts,
			Set<FcGiornata> fcGiornatasForIdAttoreFuori,
			Set<FcGiornata> fcGiornatasForIdAttoreCasa) {
		this.idAttore = idAttore;
		this.cellulare = cellulare;
		this.cognome = cognome;
		this.descAttore = descAttore;
		this.username = username;
		this.email = email;
		this.nome = nome;
		this.notifiche = notifiche;
		this.password = password;
		this.fcClassificas = fcClassificas;
		this.fcGiornataRises = fcGiornataRises;
		this.fcClassificaTotPts = fcClassificaTotPts;
		this.fcFormaziones = fcFormaziones;
		this.fcGiornataDetts = fcGiornataDetts;
		this.fcGiornataDettInfos = fcGiornataDettInfos;
		this.fcMercatoDetts = fcMercatoDetts;
		this.fcGiornatasForIdAttoreFuori = fcGiornatasForIdAttoreFuori;
		this.fcGiornatasForIdAttoreCasa = fcGiornatasForIdAttoreCasa;
	}

	@Id
	@Column(name = "id_attore", unique = true, nullable = false)
	public int getIdAttore() {
		return this.idAttore;
	}

	public void setIdAttore(int idAttore) {
		this.idAttore = idAttore;
	}

	@Column(name = "cellulare", nullable = false)
	public String getCellulare() {
		return this.cellulare;
	}

	public void setCellulare(String cellulare) {
		this.cellulare = cellulare;
	}

	@Column(name = "cognome", nullable = false)
	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	@Column(name = "desc_attore", nullable = false)
	public String getDescAttore() {
		return this.descAttore;
	}

	public void setDescAttore(String descAttore) {
		this.descAttore = descAttore;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "active")
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "notifiche", nullable = false)
	public boolean isNotifiche() {
		return this.notifiche;
	}

	@Column(name = "style")
	public String getStyle() {
		return style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public void setNotifiche(boolean notifiche) {
		this.notifiche = notifiche;
	}

	@Column(name = "admin", nullable = false)
	public boolean isAdmin() {
		return this.admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcAttore")
	public Set<FcClassifica> getFcClassificas() {
		return this.fcClassificas;
	}

	public void setFcClassificas(Set<FcClassifica> fcClassificas) {
		this.fcClassificas = fcClassificas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcAttore")
	public Set<FcGiornataRis> getFcGiornataRises() {
		return this.fcGiornataRises;
	}

	public void setFcGiornataRises(Set<FcGiornataRis> fcGiornataRises) {
		this.fcGiornataRises = fcGiornataRises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcAttore")
	public Set<FcClassificaTotPt> getFcClassificaTotPts() {
		return this.fcClassificaTotPts;
	}

	public void setFcClassificaTotPts(
			Set<FcClassificaTotPt> fcClassificaTotPts) {
		this.fcClassificaTotPts = fcClassificaTotPts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcAttore")
	public Set<FcFormazione> getFcFormaziones() {
		return this.fcFormaziones;
	}

	public void setFcFormaziones(Set<FcFormazione> fcFormaziones) {
		this.fcFormaziones = fcFormaziones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcAttore")
	public Set<FcGiornataDett> getFcGiornataDetts() {
		return this.fcGiornataDetts;
	}

	public void setFcGiornataDetts(Set<FcGiornataDett> fcGiornataDetts) {
		this.fcGiornataDetts = fcGiornataDetts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcAttore")
	public Set<FcGiornataDettInfo> getFcGiornataDettInfos() {
		return this.fcGiornataDettInfos;
	}

	public void setFcGiornataDettInfos(
			Set<FcGiornataDettInfo> fcGiornataDettInfos) {
		this.fcGiornataDettInfos = fcGiornataDettInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcAttore")
	public Set<FcMercatoDett> getFcMercatoDetts() {
		return this.fcMercatoDetts;
	}

	public void setFcMercatoDetts(Set<FcMercatoDett> fcMercatoDetts) {
		this.fcMercatoDetts = fcMercatoDetts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcAttoreByIdAttoreFuori")
	public Set<FcGiornata> getFcGiornatasForIdAttoreFuori() {
		return this.fcGiornatasForIdAttoreFuori;
	}

	public void setFcGiornatasForIdAttoreFuori(
			Set<FcGiornata> fcGiornatasForIdAttoreFuori) {
		this.fcGiornatasForIdAttoreFuori = fcGiornatasForIdAttoreFuori;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcAttoreByIdAttoreCasa")
	public Set<FcGiornata> getFcGiornatasForIdAttoreCasa() {
		return this.fcGiornatasForIdAttoreCasa;
	}

	public void setFcGiornatasForIdAttoreCasa(
			Set<FcGiornata> fcGiornatasForIdAttoreCasa) {
		this.fcGiornatasForIdAttoreCasa = fcGiornatasForIdAttoreCasa;
	}

}
