package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcCampionato generated by hbm2java
 */
@Entity
@Table(name = "fc_campionato")
public class FcCampionato implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCampionato;
	private Date dataFine;
	private Date dataInizio;
	private String descCampionato;
	private String type;
	private Integer start;
	private Integer end;
	private boolean active;
	private Set<FcClassifica> fcClassificas = new HashSet<FcClassifica>(0);
	private Set<FcClassificaTotPt> fcClassificaTotPts = new HashSet<FcClassificaTotPt>(0);
	private Set<FcFormazione> fcFormaziones = new HashSet<FcFormazione>(0);

	public FcCampionato() {
	}

	public FcCampionato(int idCampionato, String descCampionato) {
		this.idCampionato = idCampionato;
		this.descCampionato = descCampionato;
	}

	@Id

	@Column(name = "id_campionato", unique = true, nullable = false)
	public int getIdCampionato() {
		return this.idCampionato;
	}

	public void setIdCampionato(int idCampionato) {
		this.idCampionato = idCampionato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_fine", length = 10)
	public Date getDataFine() {
		return this.dataFine;
	}

	public void setDataFine(Date dataFine) {
		this.dataFine = dataFine;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_inizio", length = 10)
	public Date getDataInizio() {
		return this.dataInizio;
	}

	public void setDataInizio(Date dataInizio) {
		this.dataInizio = dataInizio;
	}

	@Column(name = "desc_campionato", nullable = false)
	public String getDescCampionato() {
		return this.descCampionato;
	}

	public void setDescCampionato(String descCampionato) {
		this.descCampionato = descCampionato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcCampionato")
	public Set<FcClassifica> getFcClassificas() {
		return this.fcClassificas;
	}

	public void setFcClassificas(Set<FcClassifica> fcClassificas) {
		this.fcClassificas = fcClassificas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcCampionato")
	public Set<FcClassificaTotPt> getFcClassificaTotPts() {
		return this.fcClassificaTotPts;
	}

	public void setFcClassificaTotPts(
			Set<FcClassificaTotPt> fcClassificaTotPts) {
		this.fcClassificaTotPts = fcClassificaTotPts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcCampionato")
	public Set<FcFormazione> getFcFormaziones() {
		return this.fcFormaziones;
	}

	public void setFcFormaziones(Set<FcFormazione> fcFormaziones) {
		this.fcFormaziones = fcFormaziones;
	}

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getEnd() {
		return end;
	}

	public void setEnd(Integer end) {
		this.end = end;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}


}
