package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FcExpFreePl generated by hbm2java
 */
@Entity
@Table(name = "fc_exp_free_pl" )
public class FcExpFreePl implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String q1;
	private String q10;
	private String q2;
	private String q3;
	private String q4;
	private String q5;
	private String q6;
	private String q7;
	private String q8;
	private String q9;
	private String r1;
	private String r10;
	private String r2;
	private String r3;
	private String r4;
	private String r5;
	private String r6;
	private String r7;
	private String r8;
	private String r9;
	private String s1;
	private String s10;
	private String s2;
	private String s3;
	private String s4;
	private String s5;
	private String s6;
	private String s7;
	private String s8;
	private String s9;

	public FcExpFreePl() {
	}

	public FcExpFreePl(int id) {
		this.id = id;
	}

	public FcExpFreePl(int id, String q1, String q10, String q2, String q3,
			String q4, String q5, String q6, String q7, String q8, String q9,
			String r1, String r10, String r2, String r3, String r4, String r5,
			String r6, String r7, String r8, String r9, String s1, String s10,
			String s2, String s3, String s4, String s5, String s6, String s7,
			String s8, String s9) {
		this.id = id;
		this.q1 = q1;
		this.q10 = q10;
		this.q2 = q2;
		this.q3 = q3;
		this.q4 = q4;
		this.q5 = q5;
		this.q6 = q6;
		this.q7 = q7;
		this.q8 = q8;
		this.q9 = q9;
		this.r1 = r1;
		this.r10 = r10;
		this.r2 = r2;
		this.r3 = r3;
		this.r4 = r4;
		this.r5 = r5;
		this.r6 = r6;
		this.r7 = r7;
		this.r8 = r8;
		this.r9 = r9;
		this.s1 = s1;
		this.s10 = s10;
		this.s2 = s2;
		this.s3 = s3;
		this.s4 = s4;
		this.s5 = s5;
		this.s6 = s6;
		this.s7 = s7;
		this.s8 = s8;
		this.s9 = s9;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "q1")
	public String getQ1() {
		return this.q1;
	}

	public void setQ1(String q1) {
		this.q1 = q1;
	}

	@Column(name = "q10")
	public String getQ10() {
		return this.q10;
	}

	public void setQ10(String q10) {
		this.q10 = q10;
	}

	@Column(name = "q2")
	public String getQ2() {
		return this.q2;
	}

	public void setQ2(String q2) {
		this.q2 = q2;
	}

	@Column(name = "q3")
	public String getQ3() {
		return this.q3;
	}

	public void setQ3(String q3) {
		this.q3 = q3;
	}

	@Column(name = "q4")
	public String getQ4() {
		return this.q4;
	}

	public void setQ4(String q4) {
		this.q4 = q4;
	}

	@Column(name = "q5")
	public String getQ5() {
		return this.q5;
	}

	public void setQ5(String q5) {
		this.q5 = q5;
	}

	@Column(name = "q6")
	public String getQ6() {
		return this.q6;
	}

	public void setQ6(String q6) {
		this.q6 = q6;
	}

	@Column(name = "q7")
	public String getQ7() {
		return this.q7;
	}

	public void setQ7(String q7) {
		this.q7 = q7;
	}

	@Column(name = "q8")
	public String getQ8() {
		return this.q8;
	}

	public void setQ8(String q8) {
		this.q8 = q8;
	}

	@Column(name = "q9")
	public String getQ9() {
		return this.q9;
	}

	public void setQ9(String q9) {
		this.q9 = q9;
	}

	@Column(name = "r1")
	public String getR1() {
		return this.r1;
	}

	public void setR1(String r1) {
		this.r1 = r1;
	}

	@Column(name = "r10")
	public String getR10() {
		return this.r10;
	}

	public void setR10(String r10) {
		this.r10 = r10;
	}

	@Column(name = "r2")
	public String getR2() {
		return this.r2;
	}

	public void setR2(String r2) {
		this.r2 = r2;
	}

	@Column(name = "r3")
	public String getR3() {
		return this.r3;
	}

	public void setR3(String r3) {
		this.r3 = r3;
	}

	@Column(name = "r4")
	public String getR4() {
		return this.r4;
	}

	public void setR4(String r4) {
		this.r4 = r4;
	}

	@Column(name = "r5")
	public String getR5() {
		return this.r5;
	}

	public void setR5(String r5) {
		this.r5 = r5;
	}

	@Column(name = "r6")
	public String getR6() {
		return this.r6;
	}

	public void setR6(String r6) {
		this.r6 = r6;
	}

	@Column(name = "r7")
	public String getR7() {
		return this.r7;
	}

	public void setR7(String r7) {
		this.r7 = r7;
	}

	@Column(name = "r8")
	public String getR8() {
		return this.r8;
	}

	public void setR8(String r8) {
		this.r8 = r8;
	}

	@Column(name = "r9")
	public String getR9() {
		return this.r9;
	}

	public void setR9(String r9) {
		this.r9 = r9;
	}

	@Column(name = "s1")
	public String getS1() {
		return this.s1;
	}

	public void setS1(String s1) {
		this.s1 = s1;
	}

	@Column(name = "s10")
	public String getS10() {
		return this.s10;
	}

	public void setS10(String s10) {
		this.s10 = s10;
	}

	@Column(name = "s2")
	public String getS2() {
		return this.s2;
	}

	public void setS2(String s2) {
		this.s2 = s2;
	}

	@Column(name = "s3")
	public String getS3() {
		return this.s3;
	}

	public void setS3(String s3) {
		this.s3 = s3;
	}

	@Column(name = "s4")
	public String getS4() {
		return this.s4;
	}

	public void setS4(String s4) {
		this.s4 = s4;
	}

	@Column(name = "s5")
	public String getS5() {
		return this.s5;
	}

	public void setS5(String s5) {
		this.s5 = s5;
	}

	@Column(name = "s6")
	public String getS6() {
		return this.s6;
	}

	public void setS6(String s6) {
		this.s6 = s6;
	}

	@Column(name = "s7")
	public String getS7() {
		return this.s7;
	}

	public void setS7(String s7) {
		this.s7 = s7;
	}

	@Column(name = "s8")
	public String getS8() {
		return this.s8;
	}

	public void setS8(String s8) {
		this.s8 = s8;
	}

	@Column(name = "s9")
	public String getS9() {
		return this.s9;
	}

	public void setS9(String s9) {
		this.s9 = s9;
	}

}
