package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FcFormazioneId generated by hbm2java
 */
@Embeddable
public class FcFormazioneId implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAttore;
	private int idCampionato;
	private int ordinamento;

	public FcFormazioneId() {
	}

	public FcFormazioneId(int idAttore, int idCampionato, int ordinamento) {
		this.idAttore = idAttore;
		this.idCampionato = idCampionato;
		this.ordinamento = ordinamento;
	}

	@Column(name = "id_attore", nullable = false)
	public int getIdAttore() {
		return this.idAttore;
	}

	public void setIdAttore(int idAttore) {
		this.idAttore = idAttore;
	}

	@Column(name = "id_campionato", nullable = false)
	public int getIdCampionato() {
		return this.idCampionato;
	}

	public void setIdCampionato(int idCampionato) {
		this.idCampionato = idCampionato;
	}

	@Column(name = "ordinamento", nullable = false)
	public int getOrdinamento() {
		return this.ordinamento;
	}

	public void setOrdinamento(int ordinamento) {
		this.ordinamento = ordinamento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FcFormazioneId))
			return false;
		FcFormazioneId castOther = (FcFormazioneId) other;

		return (this.getIdAttore() == castOther.getIdAttore()) && (this.getIdCampionato() == castOther.getIdCampionato()) && (this.getOrdinamento() == castOther.getOrdinamento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAttore();
		result = 37 * result + this.getIdCampionato();
		result = 37 * result + this.getOrdinamento();
		return result;
	}

}
