package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FcPagelle generated by hbm2java
 */
@Entity
@Table(name = "fc_giornata_giocatore" )
public class FcGiornataGiocatore implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private FcGiornataGiocatoreId id;
	private FcGiocatore fcGiocatore;
	private FcGiornataInfo fcGiornataInfo;
	private boolean infortunato;
	private boolean squalificato;
	private String note;
	
	public FcGiornataGiocatore() {
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idGiocatore", column = @Column(name = "id_giocatore", nullable = false)), @AttributeOverride(name = "idGiornata", column = @Column(name = "id_giornata", nullable = false)) })
	public FcGiornataGiocatoreId getId() {
		return this.id;
	}

	public void setId(FcGiornataGiocatoreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giocatore", nullable = false, insertable = false, updatable = false)
	public FcGiocatore getFcGiocatore() {
		return this.fcGiocatore;
	}

	public void setFcGiocatore(FcGiocatore fcGiocatore) {
		this.fcGiocatore = fcGiocatore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata", nullable = false, insertable = false, updatable = false)
	public FcGiornataInfo getFcGiornataInfo() {
		return this.fcGiornataInfo;
	}

	public void setFcGiornataInfo(FcGiornataInfo fcGiornataInfo) {
		this.fcGiornataInfo = fcGiornataInfo;
	}

	@Column(name = "infortunato")
	public boolean isInfortunato() {
		return this.infortunato;
	}

	public void setInfortunato(boolean infortunato) {
		this.infortunato = infortunato;
	}
	@Column(name = "squalificato")
	public boolean isSqualificato() {
		return this.squalificato;
	}

	public void setSqualificato(boolean squalificato) {
		this.squalificato = squalificato;
	}

	@Column(name = "note", nullable = true)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}


}
