package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FcGiornataDettId generated by hbm2java
 */
@Embeddable
public class FcGiornataDettId implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAttore;
	private int idGiocatore;
	private int idGiornata;

	public FcGiornataDettId() {
	}

	public FcGiornataDettId(int idAttore, int idGiocatore, int idGiornata) {
		this.idAttore = idAttore;
		this.idGiocatore = idGiocatore;
		this.idGiornata = idGiornata;
	}

	@Column(name = "id_attore", nullable = false)
	public int getIdAttore() {
		return this.idAttore;
	}

	public void setIdAttore(int idAttore) {
		this.idAttore = idAttore;
	}

	@Column(name = "id_giocatore", nullable = false)
	public int getIdGiocatore() {
		return this.idGiocatore;
	}

	public void setIdGiocatore(int idGiocatore) {
		this.idGiocatore = idGiocatore;
	}

	@Column(name = "id_giornata", nullable = false)
	public int getIdGiornata() {
		return this.idGiornata;
	}

	public void setIdGiornata(int idGiornata) {
		this.idGiornata = idGiornata;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FcGiornataDettId))
			return false;
		FcGiornataDettId castOther = (FcGiornataDettId) other;

		return (this.getIdAttore() == castOther.getIdAttore()) && (this.getIdGiocatore() == castOther.getIdGiocatore()) && (this.getIdGiornata() == castOther.getIdGiornata());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAttore();
		result = 37 * result + this.getIdGiocatore();
		result = 37 * result + this.getIdGiornata();
		return result;
	}

}
