package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FcGiornataDett generated by hbm2java
 */
@Entity
@Table(name = "fc_giornata_dett" )
public class FcGiornataDett implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private FcGiornataDettId id;
	private FcAttore fcAttore;
	private FcGiocatore fcGiocatore;
	private FcGiornataInfo fcGiornataInfo;
	private FcPagelle fcPagelle;
	private FcStatoGiocatore fcStatoGiocatore;
	private String flagAttivo;
	private int ordinamento;
	private Double voto;

	public FcGiornataDett() {
	}

	public FcGiornataDett(FcGiornataDettId id, FcAttore fcAttore,
			FcGiocatore fcGiocatore, FcGiornataInfo fcGiornataInfo,
			FcPagelle fcPagelle, int ordinamento) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcGiocatore = fcGiocatore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.fcPagelle = fcPagelle;
		this.ordinamento = ordinamento;
	}

	public FcGiornataDett(FcGiornataDettId id, FcAttore fcAttore,
			FcGiocatore fcGiocatore, FcGiornataInfo fcGiornataInfo,
			FcPagelle fcPagelle, FcStatoGiocatore fcStatoGiocatore,
			String flagAttivo, int ordinamento, Double voto) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcGiocatore = fcGiocatore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.fcPagelle = fcPagelle;
		this.fcStatoGiocatore = fcStatoGiocatore;
		this.flagAttivo = flagAttivo;
		this.ordinamento = ordinamento;
		this.voto = voto;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idAttore", column = @Column(name = "id_attore", nullable = false)), @AttributeOverride(name = "idGiocatore", column = @Column(name = "id_giocatore", nullable = false)), @AttributeOverride(name = "idGiornata", column = @Column(name = "id_giornata", nullable = false)) })
	public FcGiornataDettId getId() {
		return this.id;
	}

	public void setId(FcGiornataDettId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_attore", nullable = false, insertable = false, updatable = false)
	public FcAttore getFcAttore() {
		return this.fcAttore;
	}

	public void setFcAttore(FcAttore fcAttore) {
		this.fcAttore = fcAttore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giocatore", nullable = false, insertable = false, updatable = false)
	public FcGiocatore getFcGiocatore() {
		return this.fcGiocatore;
	}

	public void setFcGiocatore(FcGiocatore fcGiocatore) {
		this.fcGiocatore = fcGiocatore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata", nullable = false, insertable = false, updatable = false)
	public FcGiornataInfo getFcGiornataInfo() {
		return this.fcGiornataInfo;
	}

	public void setFcGiornataInfo(FcGiornataInfo fcGiornataInfo) {
		this.fcGiornataInfo = fcGiornataInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "id_giocatore", referencedColumnName = "id_giocatore", nullable = false, insertable = false, updatable = false), @JoinColumn(name = "id_giornata", referencedColumnName = "id_giornata", nullable = false, insertable = false, updatable = false) })
	public FcPagelle getFcPagelle() {
		return this.fcPagelle;
	}

	public void setFcPagelle(FcPagelle fcPagelle) {
		this.fcPagelle = fcPagelle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_stato_giocatore")
	public FcStatoGiocatore getFcStatoGiocatore() {
		return this.fcStatoGiocatore;
	}

	public void setFcStatoGiocatore(FcStatoGiocatore fcStatoGiocatore) {
		this.fcStatoGiocatore = fcStatoGiocatore;
	}

	@Column(name = "flag_attivo")
	public String getFlagAttivo() {
		return this.flagAttivo;
	}

	public void setFlagAttivo(String flagAttivo) {
		this.flagAttivo = flagAttivo;
	}

	@Column(name = "ordinamento", nullable = false)
	public int getOrdinamento() {
		return this.ordinamento;
	}

	public void setOrdinamento(int ordinamento) {
		this.ordinamento = ordinamento;
	}

	@Column(name = "voto", precision = 22, scale = 0)
	public Double getVoto() {
		return this.voto;
	}

	public void setVoto(Double voto) {
		this.voto = voto;
	}

}
