package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcGiornataDettInfo generated by hbm2java
 */
@Entity
@Table(name = "fc_giornata_dett_info" )
public class FcGiornataDettInfo implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private FcGiornataDettInfoId id;
	private FcAttore fcAttore;
	private FcGiornataInfo fcGiornataInfo;
	private Date dataInvio;
	private boolean flagInvio;

	public FcGiornataDettInfo() {
	}

	public FcGiornataDettInfo(FcGiornataDettInfoId id, FcAttore fcAttore,
			FcGiornataInfo fcGiornataInfo, Date dataInvio, boolean flagInvio) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.dataInvio = dataInvio;
		this.flagInvio = flagInvio;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idAttore", column = @Column(name = "id_attore", nullable = false)), @AttributeOverride(name = "idGiornata", column = @Column(name = "id_giornata", nullable = false)) })
	public FcGiornataDettInfoId getId() {
		return this.id;
	}

	public void setId(FcGiornataDettInfoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_attore", nullable = false, insertable = false, updatable = false)
	public FcAttore getFcAttore() {
		return this.fcAttore;
	}

	public void setFcAttore(FcAttore fcAttore) {
		this.fcAttore = fcAttore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata", nullable = false, insertable = false, updatable = false)
	public FcGiornataInfo getFcGiornataInfo() {
		return this.fcGiornataInfo;
	}

	public void setFcGiornataInfo(FcGiornataInfo fcGiornataInfo) {
		this.fcGiornataInfo = fcGiornataInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_invio", nullable = false, length = 19)
	public Date getDataInvio() {
		return this.dataInvio;
	}

	public void setDataInvio(Date dataInvio) {
		this.dataInvio = dataInvio;
	}

	@Column(name = "flag_invio", nullable = false)
	public boolean getFlagInvio() {
		return this.flagInvio;
	}

	public void setFlagInvio(boolean flagInvio) {
		this.flagInvio = flagInvio;
	}

}
