package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FcGiornataRis generated by hbm2java
 */
@Entity
@Table(name = "fc_giornata_ris" )
public class FcGiornataRis implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private FcGiornataRisId id;
	private FcAttore fcAttore;
	private FcGiornataInfo fcGiornataInfo;
	private Integer fm;
	private Integer gf;
	private Integer gs;
	private int idRisPartita;
	private Integer nulla;
	private Integer persa;
	private Integer punti;
	private Integer vinta;
	private Integer casafuori;

	public FcGiornataRis() {
	}

	public FcGiornataRis(FcGiornataRisId id, FcAttore fcAttore,
			FcGiornataInfo fcGiornataInfo, int idRisPartita) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.idRisPartita = idRisPartita;
	}

	public FcGiornataRis(FcGiornataRisId id, FcAttore fcAttore,
			FcGiornataInfo fcGiornataInfo, Integer fm, Integer gf, Integer gs,
			int idRisPartita, Integer nulla, Integer persa, Integer punti,
			Integer vinta) {
		this.id = id;
		this.fcAttore = fcAttore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.fm = fm;
		this.gf = gf;
		this.gs = gs;
		this.idRisPartita = idRisPartita;
		this.nulla = nulla;
		this.persa = persa;
		this.punti = punti;
		this.vinta = vinta;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idAttore", column = @Column(name = "id_attore", nullable = false)), @AttributeOverride(name = "idGiornata", column = @Column(name = "id_giornata", nullable = false)) })
	public FcGiornataRisId getId() {
		return this.id;
	}

	public void setId(FcGiornataRisId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_attore", nullable = false, insertable = false, updatable = false)
	public FcAttore getFcAttore() {
		return this.fcAttore;
	}

	public void setFcAttore(FcAttore fcAttore) {
		this.fcAttore = fcAttore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata", nullable = false, insertable = false, updatable = false)
	public FcGiornataInfo getFcGiornataInfo() {
		return this.fcGiornataInfo;
	}

	public void setFcGiornataInfo(FcGiornataInfo fcGiornataInfo) {
		this.fcGiornataInfo = fcGiornataInfo;
	}

	@Column(name = "fm")
	public Integer getFm() {
		return this.fm;
	}

	public void setFm(Integer fm) {
		this.fm = fm;
	}

	@Column(name = "gf")
	public Integer getGf() {
		return this.gf;
	}

	public void setGf(Integer gf) {
		this.gf = gf;
	}

	@Column(name = "gs")
	public Integer getGs() {
		return this.gs;
	}

	public void setGs(Integer gs) {
		this.gs = gs;
	}

	@Column(name = "id_ris_partita", nullable = false)
	public int getIdRisPartita() {
		return this.idRisPartita;
	}

	public void setIdRisPartita(int idRisPartita) {
		this.idRisPartita = idRisPartita;
	}

	@Column(name = "nulla")
	public Integer getNulla() {
		return this.nulla;
	}

	public void setNulla(Integer nulla) {
		this.nulla = nulla;
	}

	@Column(name = "persa")
	public Integer getPersa() {
		return this.persa;
	}

	public void setPersa(Integer persa) {
		this.persa = persa;
	}

	@Column(name = "punti")
	public Integer getPunti() {
		return this.punti;
	}

	public void setPunti(Integer punti) {
		this.punti = punti;
	}

	@Column(name = "vinta")
	public Integer getVinta() {
		return this.vinta;
	}

	public void setVinta(Integer vinta) {
		this.vinta = vinta;
	}

	@Column(name = "casafuori")
	public Integer getCasaFuori() {
		return this.casafuori;
	}

	public void setCasaFuori(Integer casafuori) {
		this.casafuori = casafuori;
	}

}
