package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FcMercatoDett generated by hbm2java
 */
@Entity
@Table(name = "fc_mercato_dett" )
public class FcMercatoDett implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
//	@Id
//	@GeneratedValue(strategy = IDENTITY)
//	@Column(name = "id", unique = true, nullable = false)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id")
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_attore")
	private FcAttore fcAttore;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_gioc_ven")
	private FcGiocatore fcGiocatoreByIdGiocVen;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_gioc_acq")
	private FcGiocatore fcGiocatoreByIdGiocAcq;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata")
	private FcGiornataInfo fcGiornataInfo;
	
	@Column(name = "data_cambio", nullable = false)
	private LocalDateTime dataCambio;

	@Column(name = "nota")
	private String nota;

	public FcMercatoDett() {
	}

	public FcMercatoDett(FcAttore fcAttore, FcGiocatore fcGiocatoreByIdGiocVen,
			FcGiocatore fcGiocatoreByIdGiocAcq, FcGiornataInfo fcGiornataInfo,
			LocalDateTime dataCambio, String nota) {
		this.fcAttore = fcAttore;
		this.fcGiocatoreByIdGiocVen = fcGiocatoreByIdGiocVen;
		this.fcGiocatoreByIdGiocAcq = fcGiocatoreByIdGiocAcq;
		this.fcGiornataInfo = fcGiornataInfo;
		this.dataCambio = dataCambio;
		this.nota = nota;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FcAttore getFcAttore() {
		return this.fcAttore;
	}

	public void setFcAttore(FcAttore fcAttore) {
		this.fcAttore = fcAttore;
	}

	public FcGiocatore getFcGiocatoreByIdGiocVen() {
		return this.fcGiocatoreByIdGiocVen;
	}

	public void setFcGiocatoreByIdGiocVen(FcGiocatore fcGiocatoreByIdGiocVen) {
		this.fcGiocatoreByIdGiocVen = fcGiocatoreByIdGiocVen;
	}

	public FcGiocatore getFcGiocatoreByIdGiocAcq() {
		return this.fcGiocatoreByIdGiocAcq;
	}

	public void setFcGiocatoreByIdGiocAcq(FcGiocatore fcGiocatoreByIdGiocAcq) {
		this.fcGiocatoreByIdGiocAcq = fcGiocatoreByIdGiocAcq;
	}

	public FcGiornataInfo getFcGiornataInfo() {
		return this.fcGiornataInfo;
	}

	public void setFcGiornataInfo(FcGiornataInfo fcGiornataInfo) {
		this.fcGiornataInfo = fcGiornataInfo;
	}

	public LocalDateTime getDataCambio() {
		return this.dataCambio;
	}

	public void setDataCambio(LocalDateTime dataCambio) {
		this.dataCambio = dataCambio;
	}

	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

}
