package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FcPagelle generated by hbm2java
 */
@Entity
@Table(name = "fc_pagelle" )
public class FcPagelle implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private FcPagelleId id;
	private FcGiocatore fcGiocatore;
	private FcGiornataInfo fcGiornataInfo;
	private int ammonizione;
	private int assist;
	private int autorete;
	private Double cs;
	private int espulsione;
	private Double g;
	private int goalRealizzato;
	private int goalSubito;
	private int rigoreFallito;
	private int rigoreParato;
	private int rigoreSegnato;
	private Double ts;
	private int votoGiocatore;
	private int gdv;
	
	private Set<FcGiornataDett> fcGiornataDetts = new HashSet<FcGiornataDett>(0);

	public FcPagelle() {
	}

	public FcPagelle(FcPagelleId id, FcGiocatore fcGiocatore,
			FcGiornataInfo fcGiornataInfo, int ammonizione, int assist,
			int autorete, int espulsione, int goalRealizzato, int goalSubito,
			int rigoreFallito, int rigoreParato, int rigoreSegnato,
			int votoGiocatore) {
		this.id = id;
		this.fcGiocatore = fcGiocatore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.ammonizione = ammonizione;
		this.assist = assist;
		this.autorete = autorete;
		this.espulsione = espulsione;
		this.goalRealizzato = goalRealizzato;
		this.goalSubito = goalSubito;
		this.rigoreFallito = rigoreFallito;
		this.rigoreParato = rigoreParato;
		this.rigoreSegnato = rigoreSegnato;
		this.votoGiocatore = votoGiocatore;
	}

	public FcPagelle(FcPagelleId id, FcGiocatore fcGiocatore,
			FcGiornataInfo fcGiornataInfo, int ammonizione, int assist,
			int autorete, Double cs, int espulsione, Double g,
			int goalRealizzato, int goalSubito, int rigoreFallito,
			int rigoreParato, int rigoreSegnato, Double ts, int votoGiocatore,
			Set<FcGiornataDett> fcGiornataDetts) {
		this.id = id;
		this.fcGiocatore = fcGiocatore;
		this.fcGiornataInfo = fcGiornataInfo;
		this.ammonizione = ammonizione;
		this.assist = assist;
		this.autorete = autorete;
		this.cs = cs;
		this.espulsione = espulsione;
		this.g = g;
		this.goalRealizzato = goalRealizzato;
		this.goalSubito = goalSubito;
		this.rigoreFallito = rigoreFallito;
		this.rigoreParato = rigoreParato;
		this.rigoreSegnato = rigoreSegnato;
		this.ts = ts;
		this.votoGiocatore = votoGiocatore;
		this.fcGiornataDetts = fcGiornataDetts;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idGiocatore", column = @Column(name = "id_giocatore", nullable = false)), @AttributeOverride(name = "idGiornata", column = @Column(name = "id_giornata", nullable = false)) })
	public FcPagelleId getId() {
		return this.id;
	}

	public void setId(FcPagelleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giocatore", nullable = false, insertable = false, updatable = false)
	public FcGiocatore getFcGiocatore() {
		return this.fcGiocatore;
	}

	public void setFcGiocatore(FcGiocatore fcGiocatore) {
		this.fcGiocatore = fcGiocatore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata", nullable = false, insertable = false, updatable = false)
	public FcGiornataInfo getFcGiornataInfo() {
		return this.fcGiornataInfo;
	}

	public void setFcGiornataInfo(FcGiornataInfo fcGiornataInfo) {
		this.fcGiornataInfo = fcGiornataInfo;
	}

	@Column(name = "ammonizione", nullable = false)
	public int getAmmonizione() {
		return this.ammonizione;
	}

	public void setAmmonizione(int ammonizione) {
		this.ammonizione = ammonizione;
	}

	@Column(name = "assist", nullable = false)
	public int getAssist() {
		return this.assist;
	}

	public void setAssist(int assist) {
		this.assist = assist;
	}

	@Column(name = "autorete", nullable = false)
	public int getAutorete() {
		return this.autorete;
	}

	public void setAutorete(int autorete) {
		this.autorete = autorete;
	}

	@Column(name = "cs", precision = 22, scale = 0)
	public Double getCs() {
		return this.cs;
	}

	public void setCs(Double cs) {
		this.cs = cs;
	}

	@Column(name = "espulsione", nullable = false)
	public int getEspulsione() {
		return this.espulsione;
	}

	public void setEspulsione(int espulsione) {
		this.espulsione = espulsione;
	}

	@Column(name = "g", precision = 22, scale = 0)
	public Double getG() {
		return this.g;
	}

	public void setG(Double g) {
		this.g = g;
	}

	@Column(name = "goal_realizzato", nullable = false)
	public int getGoalRealizzato() {
		return this.goalRealizzato;
	}

	public void setGoalRealizzato(int goalRealizzato) {
		this.goalRealizzato = goalRealizzato;
	}

	@Column(name = "goal_subito", nullable = false)
	public int getGoalSubito() {
		return this.goalSubito;
	}

	public void setGoalSubito(int goalSubito) {
		this.goalSubito = goalSubito;
	}

	@Column(name = "rigore_fallito", nullable = false)
	public int getRigoreFallito() {
		return this.rigoreFallito;
	}

	public void setRigoreFallito(int rigoreFallito) {
		this.rigoreFallito = rigoreFallito;
	}

	@Column(name = "rigore_parato", nullable = false)
	public int getRigoreParato() {
		return this.rigoreParato;
	}

	public void setRigoreParato(int rigoreParato) {
		this.rigoreParato = rigoreParato;
	}

	@Column(name = "rigore_segnato", nullable = false)
	public int getRigoreSegnato() {
		return this.rigoreSegnato;
	}

	public void setRigoreSegnato(int rigoreSegnato) {
		this.rigoreSegnato = rigoreSegnato;
	}

	@Column(name = "ts", precision = 22, scale = 0)
	public Double getTs() {
		return this.ts;
	}

	public void setTs(Double ts) {
		this.ts = ts;
	}

	@Column(name = "voto_giocatore", nullable = false)
	public int getVotoGiocatore() {
		return this.votoGiocatore;
	}

	public void setVotoGiocatore(int votoGiocatore) {
		this.votoGiocatore = votoGiocatore;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcPagelle")
	public Set<FcGiornataDett> getFcGiornataDetts() {
		return this.fcGiornataDetts;
	}

	public void setFcGiornataDetts(Set<FcGiornataDett> fcGiornataDetts) {
		this.fcGiornataDetts = fcGiornataDetts;
	}

	@Column(name = "gdv", nullable = false)
	public int getGdv() {
		return gdv;
	}

	public void setGdv(int gdv) {
		this.gdv = gdv;
	}

}
