package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FcRisPartita generated by hbm2java
 */
@Entity
@Table(name = "fc_ris_partita" )
public class FcRisPartita implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idRisPartita;
	private String descRisPartita;

	public FcRisPartita() {
	}

	public FcRisPartita(int idRisPartita, String descRisPartita) {
		this.idRisPartita = idRisPartita;
		this.descRisPartita = descRisPartita;
	}

	@Id

	@Column(name = "id_ris_partita", unique = true, nullable = false)
	public int getIdRisPartita() {
		return this.idRisPartita;
	}

	public void setIdRisPartita(int idRisPartita) {
		this.idRisPartita = idRisPartita;
	}

	@Column(name = "desc_ris_partita", nullable = false)
	public String getDescRisPartita() {
		return this.descRisPartita;
	}

	public void setDescRisPartita(String descRisPartita) {
		this.descRisPartita = descRisPartita;
	}

}
