package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FcRuolo generated by hbm2java
 */
@Entity
@Table(name = "fc_ruolo" )
public class FcRuolo implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idRuolo;
	private String descRuolo;
	private Set<FcGiocatore> fcGiocatores = new HashSet<FcGiocatore>(0);

	public FcRuolo() {
	}

	public FcRuolo(String idRuolo, String descRuolo) {
		this.idRuolo = idRuolo;
		this.descRuolo = descRuolo;
	}

	public FcRuolo(String idRuolo, String descRuolo,
			Set<FcGiocatore> fcGiocatores) {
		this.idRuolo = idRuolo;
		this.descRuolo = descRuolo;
		this.fcGiocatores = fcGiocatores;
	}

	@Id

	@Column(name = "id_ruolo", unique = true, nullable = false)
	public String getIdRuolo() {
		return this.idRuolo;
	}

	public void setIdRuolo(String idRuolo) {
		this.idRuolo = idRuolo;
	}

	@Column(name = "desc_ruolo", nullable = false)
	public String getDescRuolo() {
		return this.descRuolo;
	}

	public void setDescRuolo(String descRuolo) {
		this.descRuolo = descRuolo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcRuolo")
	public Set<FcGiocatore> getFcGiocatores() {
		return this.fcGiocatores;
	}

	public void setFcGiocatores(Set<FcGiocatore> fcGiocatores) {
		this.fcGiocatores = fcGiocatores;
	}

}
