package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FcSquadra generated by hbm2java
 */
@Entity
@Table(name = "fc_squadra" )
public class FcSquadra implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idSquadra;
	private String nomeSquadra;
	private String nomeImg;
	private Blob img;
	private Blob img40;
	private Set<FcGiocatore> fcGiocatores = new HashSet<FcGiocatore>(0);

	public FcSquadra() {
	}

	public FcSquadra(int idSquadra, String nomeSquadra) {
		this.idSquadra = idSquadra;
		this.nomeSquadra = nomeSquadra;
	}

	public FcSquadra(int idSquadra, String nomeSquadra,
			Set<FcGiocatore> fcGiocatores) {
		this.idSquadra = idSquadra;
		this.nomeSquadra = nomeSquadra;
		this.fcGiocatores = fcGiocatores;
	}

	@Id

	@Column(name = "id_squadra", unique = true, nullable = false)
	public int getIdSquadra() {
		return this.idSquadra;
	}

	public void setIdSquadra(int idSquadra) {
		this.idSquadra = idSquadra;
	}

	@Column(name = "nome_squadra", nullable = false)
	public String getNomeSquadra() {
		return this.nomeSquadra;
	}

	public void setNomeSquadra(String nomeSquadra) {
		this.nomeSquadra = nomeSquadra;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcSquadra")
	public Set<FcGiocatore> getFcGiocatores() {
		return this.fcGiocatores;
	}

	public void setFcGiocatores(Set<FcGiocatore> fcGiocatores) {
		this.fcGiocatores = fcGiocatores;
	}
	
	@Column(name = "nome_img")
	public String getNomeImg() {
		return this.nomeImg;
	}

	public void setNomeImg(String nomeImg) {
		this.nomeImg = nomeImg;
	}
	
	@Column(name = "img")
	public Blob getImg() {
		return this.img;
	}

	public void setImg(Blob img) {
		this.img = img;
	}

	@Column(name = "img40")
	public Blob getImg40() {
		return this.img40;
	}

	public void setImg40(Blob img40) {
		this.img40 = img40;
	}

}
