package fcweb.backend.data.entity;
// Generated 31-ott-2018 12.15.29 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FcStatoGiocatore generated by hbm2java
 */
@Entity
@Table(name = "fc_stato_giocatore" )
public class FcStatoGiocatore implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idStatoGiocatore;
	private String descStatoGiocatore;
	private Set<FcGiornataDett> fcGiornataDetts = new HashSet<FcGiornataDett>(0);

	public FcStatoGiocatore() {
	}

	public FcStatoGiocatore(String idStatoGiocatore,
			String descStatoGiocatore) {
		this.idStatoGiocatore = idStatoGiocatore;
		this.descStatoGiocatore = descStatoGiocatore;
	}

	public FcStatoGiocatore(String idStatoGiocatore, String descStatoGiocatore,
			Set<FcGiornataDett> fcGiornataDetts) {
		this.idStatoGiocatore = idStatoGiocatore;
		this.descStatoGiocatore = descStatoGiocatore;
		this.fcGiornataDetts = fcGiornataDetts;
	}

	@Id

	@Column(name = "id_stato_giocatore", unique = true, nullable = false)
	public String getIdStatoGiocatore() {
		return this.idStatoGiocatore;
	}

	public void setIdStatoGiocatore(String idStatoGiocatore) {
		this.idStatoGiocatore = idStatoGiocatore;
	}

	@Column(name = "desc_stato_giocatore", nullable = false)
	public String getDescStatoGiocatore() {
		return this.descStatoGiocatore;
	}

	public void setDescStatoGiocatore(String descStatoGiocatore) {
		this.descStatoGiocatore = descStatoGiocatore;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcStatoGiocatore")
	public Set<FcGiornataDett> getFcGiornataDetts() {
		return this.fcGiornataDetts;
	}

	public void setFcGiornataDetts(Set<FcGiornataDett> fcGiornataDetts) {
		this.fcGiornataDetts = fcGiornataDetts;
	}

}
